export enum ERRORS {
  NO_ACTION = "NO_ACTION",
  NO_TOOL = "NO_TOOL",
  BAD_TOOL = "BAD_TOOL",
  BAD_ACTION = "BAD_ACTION",
  BAD_SHAPE = "BAD_SHAPE",
  BAD_SELECTION = "BAD_SELECTION",
  FAILED_DELETE = "FAILED_DELETE",
  FAILED_UPDATE = "FAILED_UPDATE",
}

export enum ACTIONS {
  CLEAR_SESSION = "CLEAR_SESSION",
  PICK_TOOL = "PICK_TOOL",
  ADD_SHAPE = "ADD_SHAPE",
  REMOVE_SHAPE = "REMOVE_SHAPE",
  SELECT_SHAPE = "SELECT_SHAPE",
  EDIT_SHAPE = "EDIT_SHAPE",
  MOVE_SHAPE = "MOVE_SHAPE",
  RESIZE_SHAPE = "RESIZE_SHAPE",
  HAS_JS = "HAS_JS",
}

export enum APP_TOOLS {
  SELECT = "SELECT",
}
